from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class NianTrueAssets: 


	# Click Rule Assets
	# description 
	C_CLIC_SAFE = RuleClick(roi_front=(242,25,100,65), roi_back=(242,25,100,65), name="clic_safe")


	# Image Rule Assets
	# 等待进入，也是关闭按钮 
	I_N_WAITING = RuleImage(roi_front=(735,28,54,51), roi_back=(735,28,54,51), threshold=0.7, method="Template matching", file="./tasks/NianTrue/nian/nian_n_waiting.png")
	# 华北年兽 
	I_N_HUABEI = RuleImage(roi_front=(409,330,156,45), roi_back=(409,330,156,45), threshold=0.8, method="Template matching", file="./tasks/NianTrue/nian/nian_n_huabei.png")
	# 年兽战斗结束，通关奖励 
	I_BATTLE_OVER = RuleImage(roi_front=(531,212,205,61), roi_back=(531,212,205,61), threshold=0.8, method="Template matching", file="./tasks/NianTrue/nian/nian_battle_over.png")
	# 年兽来袭页面 
	I_N_PAGE = RuleImage(roi_front=(86,11,132,44), roi_back=(85,10,134,47), threshold=0.6, method="Template matching", file="./tasks/NianTrue/nian/n_page.png")
	# 年兽战斗结束，已经拥有转为金币，点击确认 
	I_N_OK = RuleImage(roi_front=(593,442,100,65), roi_back=(593,442,100,65), threshold=0.8, method="Template matching", file="./tasks/NianTrue/nian/nian_n_ok.png")


