from module.atom.click import RuleClick
from module.atom.image import RuleImage
from module.atom.list import RuleList
from module.atom.long_click import RuleLongClick
from module.atom.ocr import RuleOcr
from module.atom.swipe import RuleSwipe

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.


class ActivityShikigamiAssets:

    # Click Rule Assets
    C_RANDOM_LEFT = RuleClick(roi_front=(17, 84, 104, 356), roi_back=(17, 81, 106, 365), name="random_left")
    C_RANDOM_RIGHT = RuleClick(roi_front=(1133, 88, 131, 361), roi_back=(1131, 84, 133, 363), name="random_right")
    C_RANDOM_TOP = RuleClick(roi_front=(126, 66, 989, 58), roi_back=(123, 65, 991, 58), name="random_top")
    C_RANDOM_BOTTOM = RuleClick(roi_front=(196, 598, 581, 78), roi_back=(194, 597, 583, 81), name="random_bottom")
    C_RANDOM_ALL = RuleClick(roi_front=(42, 94, 1207, 543), roi_back=(42, 94, 1207, 543), name="random_all")

    # Image Rule Assets
    I_LOCK = RuleImage(
        roi_front=(911, 645, 21, 23),
        roi_back=(685, 612, 330, 86),
        threshold=0.7,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_lock.png",
    )
    I_UNLOCK = RuleImage(
        roi_front=(884, 648, 28, 25),
        roi_back=(686, 610, 313, 92),
        threshold=0.7,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_unlock.png",
    )
    I_CLIMB_MODE_PASS = RuleImage(
        roi_front=(1152, 638, 21, 21),
        roi_back=(1118, 510, 119, 186),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_climb_mode_pass.png",
    )
    I_CLIMB_MODE_AP = RuleImage(
        roi_front=(1190, 673, 22, 25),
        roi_back=(1055, 495, 202, 219),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_climb_mode_ap.png",
    )
    I_CLIMB_MODE_SWITCH = RuleImage(
        roi_front=(1237, 532, 29, 26),
        roi_back=(1174, 511, 104, 82),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_climb_mode_switch.png",
    )
    I_CLIMB_MODE_AP100 = RuleImage(
        roi_front=(1186, 665, 22, 25),
        roi_back=(1055, 495, 202, 219),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_climb_mode_ap100.png",
    )
    I_AP_UNLOCK = RuleImage(
        roi_front=(788, 656, 22, 25),
        roi_back=(686, 610, 313, 92),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_ap_unlock.png",
    )
    I_AP_LOCK = RuleImage(
        roi_front=(788, 656, 22, 25),
        roi_back=(686, 610, 313, 92),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_ap_lock.png",
    )
    I_ACT_FIRE = RuleImage(
        roi_front=(1135, 597, 92, 42),
        roi_back=(1080, 530, 192, 190),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_act_fire.png",
    )

    # Image Rule Assets
    I_RM_BUY_TICKET = RuleImage(
        roi_front=(873, 472, 95, 44),
        roi_back=(843, 456, 149, 75),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_buy_ticket.png",
    )
    I_RM_BUY_REWARD = RuleImage(
        roi_front=(586, 475, 99, 39),
        roi_back=(559, 454, 150, 79),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_buy_reward.png",
    )
    I_RM_BUY_AP = RuleImage(
        roi_front=(312, 472, 94, 41),
        roi_back=(283, 459, 148, 71),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_buy_ap.png",
    )
    I_RM_THROW = RuleImage(
        roi_front=(1063, 554, 80, 29),
        roi_back=(1012, 445, 183, 196),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_throw.png",
    )
    I_RM_CHECK_THROW = RuleImage(
        roi_front=(606, 337, 76, 87),
        roi_back=(531, 253, 238, 249),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_check_throw.png",
    )
    I_RM_THROW_WIN = RuleImage(
        roi_front=(667, 317, 65, 80),
        roi_back=(608, 261, 189, 186),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_throw_win.png",
    )
    I_RM_QUESTION = RuleImage(
        roi_front=(541, 109, 212, 40),
        roi_back=(482, 30, 339, 171),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_question.png",
    )
    I_RM_FORWARD = RuleImage(
        roi_front=(550, 495, 91, 43),
        roi_back=(515, 474, 161, 100),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_forward.png",
    )
    I_RM_THROW_EQUAL = RuleImage(
        roi_front=(350, 355, 51, 75),
        roi_back=(277, 307, 189, 186),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_throw_equal.png",
    )
    I_RM_BOSS = RuleImage(
        roi_front=(595, 75, 95, 44),
        roi_back=(569, 61, 149, 75),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_boss.png",
    )
    I_RM_NO_TICKET = RuleImage(
        roi_front=(356, 113, 95, 44),
        roi_back=(322, 82, 167, 102),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_no_ticket.png",
    )

    # Ocr Rule Assets
    O_FIRE = RuleOcr(
        roi=(962, 529, 308, 171),
        area=(964, 530, 309, 171),
        mode="Full",
        method="Default",
        keyword="挑战",
        name="fire",
    )
    O_REMAIN_AP = RuleOcr(
        roi=(726, 25, 95, 34),
        area=(726, 25, 95, 34),
        mode="DigitCounter",
        method="Default",
        keyword="",
        name="remain_ap",
    )
    O_REMAIN_PASS = RuleOcr(
        roi=(1117, 26, 88, 31),
        area=(1117, 26, 88, 31),
        mode="DigitCounter",
        method="Default",
        keyword="",
        name="remain_pass",
    )
    O_REMAIN_BUY = RuleOcr(
        roi=(808, 531, 39, 42),
        area=(808, 531, 39, 42),
        mode="DigitCounter",
        method="Default",
        keyword="",
        name="remain_buy",
    )
    O_REMAIN_PASS2 = RuleOcr(
        roi=(750, 17, 88, 29),
        area=(750, 17, 88, 29),
        mode="Digit",
        method="Default",
        keyword="",
        name="remain_pass2",
    )
    O_REMAIN_BOSS = RuleOcr(
        roi=(795, 24, 95, 32),
        area=(795, 24, 95, 32),
        mode="DigitCounter",
        method="Default",
        keyword="",
        name="remain_boss",
    )
    O_REMAIN_AP100 = RuleOcr(
        roi=(978,26,48,30),
        area=(978,26,48,30),
        mode="Digit",
        method="Default",
        keyword="",
        name="remain_ap100",
    )
    O_ENTER_AP100 = RuleOcr(
        roi=(67, 99, 92, 359),
        area=(67, 99, 92, 359),
        mode="Full",
        method="Default",
        keyword="雪山修行",
        name="enter_ap100",
    )

    # Ocr Rule Assets
    O_RM_QUESTION = RuleOcr(
        roi=(358, 159, 593, 111),
        area=(358, 159, 593, 111),
        mode="Full",
        method="Default",
        keyword="",
        name="rm_question",
    )
    O_RM_ANSWER_1 = RuleOcr(
        roi=(415, 290, 468, 53),
        area=(415, 290, 468, 53),
        mode="Single",
        method="Default",
        keyword="",
        name="rm_answer_1",
    )
    O_RM_ANSWER_2 = RuleOcr(
        roi=(418, 401, 467, 53),
        area=(418, 401, 467, 53),
        mode="Single",
        method="Default",
        keyword="",
        name="rm_answer_2",
    )
    O_RM_ANSWER_3 = RuleOcr(
        roi=(418, 516, 468, 54),
        area=(418, 516, 468, 54),
        mode="Single",
        method="Default",
        keyword="",
        name="rm_answer_3",
    )

    # Image Rule Assets
    I_MAIN_GOTO_ACT = RuleImage(
        roi_front=(1185, 303, 44, 25),
        roi_back=(1164, 134, 83, 393),
        threshold=0.7,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_main_goto_act.png",
    )
    I_SKIP_BUTTON = RuleImage(
        roi_front=(1159, 37, 51, 22),
        roi_back=(1141, 27, 86, 43),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_skip_button.png",
    )
    I_TO_BATTLE_MAIN = RuleImage(
        roi_front=(444, 223, 39, 139),
        roi_back=(367, 166, 238, 269),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_to_battle_main.png",
    )
    I_TO_BATTLE_BOSS = RuleImage(
        roi_front=(1079, 186, 37, 136),
        roi_back=(971, 91, 234, 327),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_to_battle_boss.png",
    )
    I_CHECK_BATTLE_BOSS = RuleImage(
        roi_front=(1209, 494, 26, 31),
        roi_back=(1172, 458, 100, 100),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_check_battle_boss.png",
    )
    I_BATTLE_MAIN_TO_RECORDS = RuleImage(
        roi_front=(1027, 557, 39, 42),
        roi_back=(674, 539, 439, 157),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_battle_main_to_records.png",
    )
    I_AS_TO_PASS = RuleImage(
        roi_front=(575, 267, 38, 35),
        roi_back=(273, 141, 759, 475),
        threshold=0.65,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_as_to_pass.png",
    )
    I_CONFIRM_SKIP = RuleImage(
        roi_front=(707, 442, 137, 38),
        roi_back=(656, 397, 231, 124),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_confirm_skip.png",
    )
    I_RM_CHECK_BOSS = RuleImage(
        roi_front=(988, 599, 75, 29),
        roi_back=(952, 546, 142, 115),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_rm_check_boss.png",
    )
    I_AS_CHECK_MAIN_2 = RuleImage(
        roi_front=(566, 10, 151, 36),
        roi_back=(505, 0, 256, 92),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_as_check_main_2.png",
    )
    I_AS_OPEN_EYE = RuleImage(
        roi_front=(1198, 300, 60, 54),
        roi_back=(1146, 253, 134, 217),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_as_open_eye.png",
    )
    I_AS_LOCATE = RuleImage(
        roi_front=(1212, 394, 34, 36),
        roi_back=(1146, 253, 134, 217),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_as_locate.png",
    )
    I_AS_CLOSE_EYE = RuleImage(
        roi_front=(1197, 297, 63, 57),
        roi_back=(1146, 253, 134, 217),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_as_close_eye.png",
    )
    I_TO_BATTLE_AP = RuleImage(
        roi_front=(825, 321, 39, 139),
        roi_back=(720, 255, 238, 269),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_to_battle_ap.png",
    )

    # 兼容旧调用
    I_SHI = I_MAIN_GOTO_ACT
    I_BACK_GREEN = RuleImage(
        roi_front=(27, 19, 34, 38),
        roi_back=(2, 1, 170, 75),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_back_green.png",
    )
    I_RED_EXIT = RuleImage(
        roi_front=(1162, 96, 39, 38),
        roi_back=(939, 49, 291, 166),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_red_exit.png",
    )
    I_CHECK_BATTLE_MAIN = RuleImage(
        roi_front=(1149, 596, 81, 77),
        roi_back=(865, 508, 415, 203),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_check_battle_main.png",
    )
    I_TO_BATTLE_MAIN_2 = RuleImage(
        roi_front=(15, 94, 247, 38),
        roi_back=(2, 68, 311, 100),
        threshold=0.65,
        method="Template matching",
        file="./tasks/ActivityShikigami/as/as_to_battle_main_2.png",
    )

    # Image Rule Assets
    I_PASS_1 = RuleImage(
        roi_front=(359, 295, 100, 53),
        roi_back=(68, 203, 1138, 369),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_1.png",
    )
    I_PASS_2 = RuleImage(
        roi_front=(645, 224, 92, 57),
        roi_back=(98, 205, 1076, 366),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_2.png",
    )
    I_PASS_3 = RuleImage(
        roi_front=(648, 227, 91, 55),
        roi_back=(103, 162, 1077, 416),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_3.png",
    )
    I_PASS_4 = RuleImage(
        roi_front=(586, 424, 100, 58),
        roi_back=(99, 194, 1080, 398),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_4.png",
    )
    I_PASS_5 = RuleImage(
        roi_front=(946, 415, 65, 48),
        roi_back=(97, 194, 1036, 398),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_5.png",
    )
    I_PASS_6 = RuleImage(
        roi_front=(668, 221, 54, 50),
        roi_back=(107, 159, 1012, 394),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_6.png",
    )
    I_PASS_7 = RuleImage(
        roi_front=(329, 233, 51, 51),
        roi_back=(95, 180, 1056, 394),
        threshold=0.65,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_7.png",
    )
    I_PASS_8 = RuleImage(
        roi_front=(579, 276, 100, 100),
        roi_back=(577, 296, 100, 100),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_8.png",
    )
    I_PASS_9 = RuleImage(
        roi_front=(558, 643, 160, 44),
        roi_back=(480, 601, 306, 100),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_9.png",
    )
    I_PASS_10 = RuleImage(
        roi_front=(279, 309, 100, 100),
        roi_back=(291, 305, 100, 100),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_10.png",
    )
    I_PASS_11 = RuleImage(
        roi_front=(918, 304, 100, 100),
        roi_back=(914, 308, 100, 100),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_11.png",
    )
    I_PASS12 = RuleImage(
        roi_front=(870, 356, 100, 50),
        roi_back=(104, 169, 1109, 425),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass12.png",
    )
    I_PASS_13 = RuleImage(
        roi_front=(1018, 570, 100, 100),
        roi_back=(984, 538, 261, 167),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_pass_13.png",
    )
    I_RICH_MAN_FIRE = RuleImage(
        roi_front=(983, 555, 82, 78),
        roi_back=(924, 479, 225, 213),
        threshold=0.8,
        method="Template matching",
        file="./tasks/ActivityShikigami/fire/fire_rich_man_fire.png",
    )