from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class AutoCakeAssets: 


	# Click Rule Assets
	# 樱饼区域 
	C_CAKE_AREA = RuleClick(roi_front=(968,660,23,22), roi_back=(968,660,23,22), name="cake_area")


	# Image Rule Assets
	# 进入活动第二步 
	I_STEP_2 = RuleImage(roi_front=(207,210,37,138), roi_back=(207,210,37,138), threshold=0.8, method="Template matching", file="./tasks/AutoCake/res/res_step_2.png")
	# 是否到达活动界面 
	I_IS_REACH = RuleImage(roi_front=(87,16,130,41), roi_back=(87,16,130,41), threshold=0.8, method="Template matching", file="./tasks/AutoCake/res/res_is_reach.png")
	# description 
	I_IS_OVER = RuleImage(roi_front=(706,254,69,64), roi_back=(706,254,69,64), threshold=0.8, method="Template matching", file="./tasks/AutoCake/res/res_is_over.png")
	# 已关闭樱饼 
	I_IS_CLOSE = RuleImage(roi_front=(970,663,22,21), roi_back=(970,663,22,21), threshold=0.6, method="Template matching", file="./tasks/AutoCake/res/res_is_close.png")
	# 上锁 
	I_LOCK = RuleImage(roi_front=(912,657,21,25), roi_back=(658,588,437,127), threshold=0.8, method="Template matching", file="./tasks/AutoCake/res/res_lock.png")
	# 未上锁 
	I_UNLOCK = RuleImage(roi_front=(909,661,22,21), roi_back=(774,619,330,100), threshold=0.8, method="Template matching", file="./tasks/AutoCake/res/res_unlock.png")


