# This Python file uses the following encoding: utf-8
# @author runhey
# github https://github.com/runhey

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class MultiAccountDailyAssets:
    pass

