from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GoryouRealmAssets: 


	# Click Rule Assets
	# description 
	C_GR_C_1 = RuleClick(roi_front=(111,77,206,431), roi_back=(111,77,206,431), name="gr_c_1")
	# description 
	C_GR_C_2 = RuleClick(roi_front=(413,76,209,342), roi_back=(413,76,209,342), name="gr_c_2")
	# description 
	C_GR_C_3 = RuleClick(roi_front=(725,97,195,401), roi_back=(725,97,195,401), name="gr_c_3")
	# description 
	C_GR_C_4 = RuleClick(roi_front=(1026,82,206,334), roi_back=(1026,82,206,334), name="gr_c_4")


	# Image Rule Assets
	# 点击挑战 
	I_GR_FIRE = RuleImage(roi_front=(1057,584,88,89), roi_back=(1012,557,183,148), threshold=0.8, method="Template matching", file="./tasks/GoryouRealm/gr/gr_gr_fire.png")
	# description 
	I_GR_LOCK = RuleImage(roi_front=(701,657,27,32), roi_back=(665,629,99,91), threshold=0.5, method="Template matching", file="./tasks/GoryouRealm/gr/gr_gr_lock.png")
	# description 
	I_GR_UNLOCK = RuleImage(roi_front=(705,656,20,30), roi_back=(671,636,84,73), threshold=0.8, method="Template matching", file="./tasks/GoryouRealm/gr/gr_gr_unlock.png")


	# Ocr Rule Assets
	# 多少张票 
	O_GR_TICKET = RuleOcr(roi=(935,13,95,32), area=(935,13,95,32), mode="Digit", method="Default", keyword="", name="gr_ticket")


