from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class EvoZoneAssets: 


	# Image Rule Assets
	# 火麒麟进入 
	I_FIRE_KIRIN = RuleImage(roi_front=(127,176,139,252), roi_back=(106,121,217,406), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_fire_kirin.png")
	# 组队 
	I_FORM_TEAM = RuleImage(roi_front=(961,602,96,55), roi_back=(937,555,153,154), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_form_team.png")
	# description 
	I_EVOZONE_LOCK = RuleImage(roi_front=(703,656,24,32), roi_back=(683,646,63,64), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_evozone_lock.png")
	# description 
	I_EVOZONE_UNLOCK = RuleImage(roi_front=(704,658,21,27), roi_back=(680,643,67,67), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_evozone_unlock.png")
	# 点击挑战 
	I_EVOZONE_FIRE = RuleImage(roi_front=(1146,595,93,50), roi_back=(1125,570,131,124), threshold=0.6, method="Template matching", file="./tasks/EvoZone/o/o_evozone_fire.png")
	# 式神录 
	I_SHI_RECORDS = RuleImage(roi_front=(844,569,43,43), roi_back=(827,559,79,74), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_shi_records.png")
	# 小小宠物，发现宝藏 
	I_PET_PRESENT = RuleImage(roi_front=(873,184,62,147), roi_back=(873,184,62,147), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_pet_present.png")
	# 风麒麟进入 
	I_WIND_KIRIN = RuleImage(roi_front=(445,114,139,252), roi_back=(411,77,217,406), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_wind_kirin.png")
	# 水麒麟进入 
	I_WATER_KIRIN = RuleImage(roi_front=(743,182,139,252), roi_back=(710,121,217,406), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_water_kirin.png")
	# 雷麒麟进入 
	I_LIGHTNING_KIRIN = RuleImage(roi_front=(1051,111,139,252), roi_back=(1013,85,217,406), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_lightning_kirin.png")


	# List Rule Assets
	# 这个是觉醒界面选择不同层数的 
	L_LAYER_LIST = RuleList(folder="./tasks/EvoZone/res", direction="vertical", mode="ocr", roi_back=(130,124,64,581), size=(64, 98), 
					 array=["壹", "贰", "叁", "肆", "伍", "陆", "柒", "捌", "玖", "拾"])


	# Ocr Rule Assets
	# Ocr-description 
	O_O_TEST_OCR = RuleOcr(roi=(126,136,360,491), area=(126,136,360,491), mode="Full", method="Default", keyword="", name="o_test_ocr")


